# This file contains configuration options for golangci linter
# Any options can be override creating a .golangci-.yml file
# in deeper levels of the hierarchy path

# linter settings
linter-settings:
  go-vet:
    # report about shadowed variables
    check-shadowing: true

# enable or disable specific linters
linters:
  enable:
    - gosec
    - staticcheck
    - nakedret
    - stylecheck
    - goconst
    - gocyclo

    # List of regexps of issue texts to exclude
issues:
  # Excluding configuration per path
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

run:
  # give it 1 min timeout
  timeout: 1m
  
  # skip the following files
  skip-files:
    - "_protoactor\\.go$" 
