---
api:
  address: "0.0.0.0:80"
database:
  kind: redis
  redis:
    address: "redis:6379"
    password: "test"
    database: 0
    retries: 3
    interval: 1s
nats:
  address: "nats:4222"
  default_subject: "updates"