version: '3'

services:
    redis:
        image: bitnami/redis:6.2
        environment:
            - "REDIS_PASSWORD=test"
        ports:
            - 6379:6379
    nats:
        image: bitnami/nats:2.3.4
        ports:
            - 4222:4222
            - 6222:6222
            - 8222:8222
