version: '3'

services:
    redis:
        image: bitnami/redis:6.2
        environment:
            - "REDIS_PASSWORD=test"
        networks:
            - scheduler
        ports:
            - 6379:6379
        volumes:
            - redis_data:/bitnami/redis/data
    nats:
        image: bitnami/nats:2.3.4
        ports:
            - 4222:4222
            - 6222:6222
            - 8222:8222
        networks:
            - scheduler
    scheduler:
        image: scheduler:0.1.0
        ports:
            - 80:80
        networks:
            - scheduler
        volumes:
            - ../config.yaml:/etc/config.yaml
        command: "-config /etc/config.yaml"

networks:
    scheduler:

volumes:
    redis_data:
        driver: local
