version: '3'

services:
    etcd:
        image: bitnami/etcd:3
        environment:
            - "ALLOW_NONE_AUTHENTICATION=yes"
        volumes:
            - etcd_data:/bitnami/etcd
        ports:
            - 22379:2379

volumes:
    etcd_data:
        driver: local
